language: node_js
node_js:
- stable
notifications:
  slack:
    secure: SI4GUt2bPPf0GMYvpYF1I9hwMYuHryr6PuFrClNhWCgQEUNupOz1uxUgvmOSbXrHAnxOlTPiP/q4m1yzMggw1uXoS/Zh7an1YofPc4Mkg7MOaDZ/1lCQ5bjTY2eMWC3v9e6xtyeS81K/fXSranCazwRFXscBsFixL2d3YWc5xryceU077rnB1U7CI8OMaoiUtRfP81+tDmYv+6UVp8jg5IPD60C506Iv/ubZYk3HTtTf60nNs20w9+edwokCjQF3LZbCmI9n8U3kohpKd7eMagOwIhO97Ozws5rRXoztt6SUqh7ELB5y/hMXTXv1dj5RUJknMj8AZOQ8jcG5JBKKetdP53qpdiUijh2ikt9grpEzYuI2ErIiMthDbVn2Vojj8q5mdHmPMixnXZzh6CbJe1IraWUu5w6p/OMmCfl2d35ALyDgZRMC6x8Ko9VIHSJ5b7ryyTcmDOxxJQGe2D/fhWb2G7z3ZsBfdYW2DrsYfvUcU4pQHlaHfeeHKKtom/b9CZ7b3TaAqmzYS32J2aAvbeuVaKjXGH+WcsklnQI5rLn9WGH0lbXNSrNs6yHZosbmoQtv3UHU6cJp335PCzOJ95xLQnnw2mzB13tFfczrBBlheSGvoA68HwNMy9pJAQQXay6U9BPCd89cDG1Z8Fi2zzJqgusXcY8SmJY6uxDqG5k=
  email: false